// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  kind: __t.string(),
  url: __t.string(),
  thumb: __t.string(),
  art: __t.string(),
  caption: __t.string(),
  day: __t.string(),
  charm: __t.string(),
  w: __t.u32(),
  h: __t.u32(),
  by: __t.string(),
};
