// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  kind: __t.string(),
  round: __t.u64(),
  cells: __t.string(),
  faces: __t.string(),
  turn: __t.string(),
  first: __t.string(),
  second: __t.string(),
  winner: __t.string(),
  line: __t.string(),
  moves: __t.u32(),
  open: __t.string(),
  scoreFirst: __t.u32().name("score_first"),
  scoreSecond: __t.u32().name("score_second"),
  at: __t.timestamp(),
});
