// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.4.1 (commit 07b52763c9da8d7cf79780db222fec1ffcb84070).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptCallReducer from "./accept_call_reducer";
import AddJokeReducer from "./add_joke_reducer";
import AddScrapReducer from "./add_scrap_reducer";
import BeatReducer from "./beat_reducer";
import BoardEndReducer from "./board_end_reducer";
import BoardMoveReducer from "./board_move_reducer";
import BoardSettleReducer from "./board_settle_reducer";
import BoardStartReducer from "./board_start_reducer";
import ClearNightReducer from "./clear_night_reducer";
import ClearThreadReducer from "./clear_thread_reducer";
import DeleteMessageReducer from "./delete_message_reducer";
import DoodleClearReducer from "./doodle_clear_reducer";
import DoodlePaintReducer from "./doodle_paint_reducer";
import DoodlePromptReducer from "./doodle_prompt_reducer";
import EditMessageReducer from "./edit_message_reducer";
import EditScrapReducer from "./edit_scrap_reducer";
import EndGameReducer from "./end_game_reducer";
import HangUpReducer from "./hang_up_reducer";
import MarkNightReducer from "./mark_night_reducer";
import MarkReadReducer from "./mark_read_reducer";
import NameUsReducer from "./name_us_reducer";
import NextRoundReducer from "./next_round_reducer";
import RemoveJokeReducer from "./remove_joke_reducer";
import RemoveScrapReducer from "./remove_scrap_reducer";
import RestReducer from "./rest_reducer";
import RevealRoundReducer from "./reveal_round_reducer";
import RingReducer from "./ring_reducer";
import SealScrapReducer from "./seal_scrap_reducer";
import SendMessageReducer from "./send_message_reducer";
import SendSignalReducer from "./send_signal_reducer";
import SetLayoutReducer from "./set_layout_reducer";
import SetTypingReducer from "./set_typing_reducer";
import StartGameReducer from "./start_game_reducer";
import SubmitAnswerReducer from "./submit_answer_reducer";
import UnlockPlusReducer from "./unlock_plus_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import BoardRow from "./board_table";
import BoardTallyRow from "./board_tally_table";
import CallRow from "./call_table";
import CoupleRow from "./couple_table";
import DoodleRow from "./doodle_table";
import GameRow from "./game_table";
import GameAnswerRow from "./game_answer_table";
import GameScoreRow from "./game_score_table";
import JokeRow from "./joke_table";
import KeycheckRow from "./keycheck_table";
import MessageRow from "./message_table";
import MetaRow from "./meta_table";
import NightRow from "./night_table";
import PlusRow from "./plus_table";
import PresenceRow from "./presence_table";
import PulseRow from "./pulse_table";
import ReadMarkerRow from "./read_marker_table";
import ScrapRow from "./scrap_table";
import ScrapLayoutRow from "./scrap_layout_table";
import SignalRow from "./signal_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  board: __table({
    name: 'board',
    indexes: [
      { accessor: 'id', name: 'board_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'board_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BoardRow),
  board_tally: __table({
    name: 'board_tally',
    indexes: [
      { accessor: 'key', name: 'board_tally_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'board_tally_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, BoardTallyRow),
  call: __table({
    name: 'call',
    indexes: [
      { accessor: 'id', name: 'call_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'call_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CallRow),
  couple: __table({
    name: 'couple',
    indexes: [
      { accessor: 'id', name: 'couple_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'couple_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CoupleRow),
  doodle: __table({
    name: 'doodle',
    indexes: [
      { accessor: 'id', name: 'doodle_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'doodle_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DoodleRow),
  game: __table({
    name: 'game',
    indexes: [
      { accessor: 'id', name: 'game_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameRow),
  game_answer: __table({
    name: 'game_answer',
    indexes: [
      { accessor: 'key', name: 'game_answer_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'game_answer_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, GameAnswerRow),
  game_score: __table({
    name: 'game_score',
    indexes: [
      { accessor: 'who', name: 'game_score_who_idx_btree', algorithm: 'btree', columns: [
        'who',
      ] },
    ],
    constraints: [
      { name: 'game_score_who_key', constraint: 'unique', columns: ['who'] },
    ],
  }, GameScoreRow),
  joke: __table({
    name: 'joke',
    indexes: [
      { accessor: 'id', name: 'joke_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'joke_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, JokeRow),
  keycheck: __table({
    name: 'keycheck',
    indexes: [
      { accessor: 'id', name: 'keycheck_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'keycheck_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, KeycheckRow),
  message: __table({
    name: 'message',
    indexes: [
      { accessor: 'id', name: 'message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MessageRow),
  meta: __table({
    name: 'meta',
    indexes: [
      { accessor: 'id', name: 'meta_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'meta_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MetaRow),
  night: __table({
    name: 'night',
    indexes: [
      { accessor: 'day', name: 'night_day_idx_btree', algorithm: 'btree', columns: [
        'day',
      ] },
    ],
    constraints: [
      { name: 'night_day_key', constraint: 'unique', columns: ['day'] },
    ],
  }, NightRow),
  plus: __table({
    name: 'plus',
    indexes: [
      { accessor: 'id', name: 'plus_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'plus_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlusRow),
  presence: __table({
    name: 'presence',
    indexes: [
      { accessor: 'who', name: 'presence_who_idx_btree', algorithm: 'btree', columns: [
        'who',
      ] },
    ],
    constraints: [
      { name: 'presence_who_key', constraint: 'unique', columns: ['who'] },
    ],
  }, PresenceRow),
  pulse: __table({
    name: 'pulse',
    indexes: [
      { accessor: 'who', name: 'pulse_who_idx_btree', algorithm: 'btree', columns: [
        'who',
      ] },
    ],
    constraints: [
      { name: 'pulse_who_key', constraint: 'unique', columns: ['who'] },
    ],
  }, PulseRow),
  read_marker: __table({
    name: 'read_marker',
    indexes: [
      { accessor: 'who', name: 'read_marker_who_idx_btree', algorithm: 'btree', columns: [
        'who',
      ] },
    ],
    constraints: [
      { name: 'read_marker_who_key', constraint: 'unique', columns: ['who'] },
    ],
  }, ReadMarkerRow),
  scrap: __table({
    name: 'scrap',
    indexes: [
      { accessor: 'id', name: 'scrap_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'scrap_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ScrapRow),
  scrap_layout: __table({
    name: 'scrap_layout',
    indexes: [
      { accessor: 'scrap_id', name: 'scrap_layout_scrap_id_idx_btree', algorithm: 'btree', columns: [
        'scrapId',
      ] },
    ],
    constraints: [
      { name: 'scrap_layout_scrap_id_key', constraint: 'unique', columns: ['scrapId'] },
    ],
  }, ScrapLayoutRow),
  signal: __table({
    name: 'signal',
    indexes: [
      { accessor: 'id', name: 'signal_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'signal_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SignalRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_call", AcceptCallReducer),
  __reducerSchema("add_joke", AddJokeReducer),
  __reducerSchema("add_scrap", AddScrapReducer),
  __reducerSchema("beat", BeatReducer),
  __reducerSchema("board_end", BoardEndReducer),
  __reducerSchema("board_move", BoardMoveReducer),
  __reducerSchema("board_settle", BoardSettleReducer),
  __reducerSchema("board_start", BoardStartReducer),
  __reducerSchema("clear_night", ClearNightReducer),
  __reducerSchema("clear_thread", ClearThreadReducer),
  __reducerSchema("delete_message", DeleteMessageReducer),
  __reducerSchema("doodle_clear", DoodleClearReducer),
  __reducerSchema("doodle_paint", DoodlePaintReducer),
  __reducerSchema("doodle_prompt", DoodlePromptReducer),
  __reducerSchema("edit_message", EditMessageReducer),
  __reducerSchema("edit_scrap", EditScrapReducer),
  __reducerSchema("end_game", EndGameReducer),
  __reducerSchema("hang_up", HangUpReducer),
  __reducerSchema("mark_night", MarkNightReducer),
  __reducerSchema("mark_read", MarkReadReducer),
  __reducerSchema("name_us", NameUsReducer),
  __reducerSchema("next_round", NextRoundReducer),
  __reducerSchema("remove_joke", RemoveJokeReducer),
  __reducerSchema("remove_scrap", RemoveScrapReducer),
  __reducerSchema("rest", RestReducer),
  __reducerSchema("reveal_round", RevealRoundReducer),
  __reducerSchema("ring", RingReducer),
  __reducerSchema("seal_scrap", SealScrapReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("send_signal", SendSignalReducer),
  __reducerSchema("set_layout", SetLayoutReducer),
  __reducerSchema("set_typing", SetTypingReducer),
  __reducerSchema("start_game", StartGameReducer),
  __reducerSchema("submit_answer", SubmitAnswerReducer),
  __reducerSchema("unlock_plus", UnlockPlusReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.4.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

