// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Board = __t.object("Board", {
  id: __t.u32(),
  kind: __t.string(),
  round: __t.u64(),
  cells: __t.string(),
  faces: __t.string(),
  turn: __t.string(),
  first: __t.string(),
  second: __t.string(),
  winner: __t.string(),
  line: __t.string(),
  moves: __t.u32(),
  open: __t.string(),
  scoreFirst: __t.u32(),
  scoreSecond: __t.u32(),
  at: __t.timestamp(),
});
export type Board = __Infer<typeof Board>;

export const BoardSecret = __t.object("BoardSecret", {
  id: __t.u32(),
  deck: __t.string(),
});
export type BoardSecret = __Infer<typeof BoardSecret>;

export const BoardTally = __t.object("BoardTally", {
  key: __t.string(),
  kind: __t.string(),
  who: __t.string(),
  wins: __t.u64(),
});
export type BoardTally = __Infer<typeof BoardTally>;

export const Call = __t.object("Call", {
  id: __t.u32(),
  status: __t.string(),
  caller: __t.string(),
  at: __t.timestamp(),
});
export type Call = __Infer<typeof Call>;

export const Couple = __t.object("Couple", {
  id: __t.u32(),
  moonName: __t.string(),
  starName: __t.string(),
  namedAt: __t.timestamp(),
});
export type Couple = __Infer<typeof Couple>;

export const Doodle = __t.object("Doodle", {
  id: __t.u32(),
  size: __t.u32(),
  cells: __t.string(),
  sheet: __t.u64(),
  prompt: __t.string(),
  by: __t.string(),
  at: __t.timestamp(),
});
export type Doodle = __Infer<typeof Doodle>;

export const Game = __t.object("Game", {
  id: __t.u32(),
  kind: __t.string(),
  round: __t.u64(),
  prompt: __t.string(),
  options: __t.string(),
  phase: __t.string(),
  turn: __t.string(),
  at: __t.timestamp(),
});
export type Game = __Infer<typeof Game>;

export const GameAnswer = __t.object("GameAnswer", {
  key: __t.string(),
  round: __t.u64(),
  who: __t.string(),
  answer: __t.string(),
  at: __t.timestamp(),
});
export type GameAnswer = __Infer<typeof GameAnswer>;

export const GameScore = __t.object("GameScore", {
  who: __t.string(),
  matches: __t.u64(),
  rounds: __t.u64(),
});
export type GameScore = __Infer<typeof GameScore>;

export const Joke = __t.object("Joke", {
  id: __t.u64(),
  text: __t.string(),
  by: __t.string(),
  at: __t.timestamp(),
});
export type Joke = __Infer<typeof Joke>;

export const Keycheck = __t.object("Keycheck", {
  id: __t.u32(),
  canary: __t.string(),
  iv: __t.string(),
  salt: __t.string(),
});
export type Keycheck = __Infer<typeof Keycheck>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  body: __t.string(),
  iv: __t.string(),
  by: __t.string(),
  at: __t.timestamp(),
  edited: __t.bool(),
});
export type Message = __Infer<typeof Message>;

export const Meta = __t.object("Meta", {
  id: __t.u32(),
  startedOn: __t.string(),
});
export type Meta = __Infer<typeof Meta>;

export const Night = __t.object("Night", {
  day: __t.string(),
  kind: __t.string(),
  note: __t.string(),
  by: __t.string(),
  at: __t.timestamp(),
});
export type Night = __Infer<typeof Night>;

export const Plus = __t.object("Plus", {
  id: __t.u32(),
  active: __t.bool(),
  by: __t.string(),
  at: __t.timestamp(),
});
export type Plus = __Infer<typeof Plus>;

export const Presence = __t.object("Presence", {
  who: __t.string(),
  typing: __t.bool(),
  at: __t.timestamp(),
});
export type Presence = __Infer<typeof Presence>;

export const Pulse = __t.object("Pulse", {
  who: __t.string(),
  active: __t.bool(),
  place: __t.string(),
  conn: __t.string(),
  at: __t.timestamp(),
});
export type Pulse = __Infer<typeof Pulse>;

export const ReadMarker = __t.object("ReadMarker", {
  who: __t.string(),
  lastSeen: __t.u64(),
});
export type ReadMarker = __Infer<typeof ReadMarker>;

export const Scrap = __t.object("Scrap", {
  id: __t.u64(),
  kind: __t.string(),
  url: __t.string(),
  thumb: __t.string(),
  art: __t.string(),
  caption: __t.string(),
  day: __t.string(),
  charm: __t.string(),
  w: __t.u32(),
  h: __t.u32(),
  by: __t.string(),
  at: __t.timestamp(),
});
export type Scrap = __Infer<typeof Scrap>;

export const ScrapLayout = __t.object("ScrapLayout", {
  scrapId: __t.u64(),
  layout: __t.string(),
  sealedBy: __t.string(),
  sealedAt: __t.option(__t.timestamp()),
});
export type ScrapLayout = __Infer<typeof ScrapLayout>;

export const Signal = __t.object("Signal", {
  id: __t.u64(),
  from: __t.string(),
  kind: __t.string(),
  payload: __t.string(),
  at: __t.timestamp(),
});
export type Signal = __Infer<typeof Signal>;

