// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptCallReducer from "../accept_call_reducer";
import AddJokeReducer from "../add_joke_reducer";
import AddScrapReducer from "../add_scrap_reducer";
import BeatReducer from "../beat_reducer";
import BoardEndReducer from "../board_end_reducer";
import BoardMoveReducer from "../board_move_reducer";
import BoardSettleReducer from "../board_settle_reducer";
import BoardStartReducer from "../board_start_reducer";
import ClearNightReducer from "../clear_night_reducer";
import ClearThreadReducer from "../clear_thread_reducer";
import DeleteMessageReducer from "../delete_message_reducer";
import DoodleClearReducer from "../doodle_clear_reducer";
import DoodlePaintReducer from "../doodle_paint_reducer";
import DoodlePromptReducer from "../doodle_prompt_reducer";
import EditMessageReducer from "../edit_message_reducer";
import EditScrapReducer from "../edit_scrap_reducer";
import EndGameReducer from "../end_game_reducer";
import HangUpReducer from "../hang_up_reducer";
import MarkNightReducer from "../mark_night_reducer";
import MarkReadReducer from "../mark_read_reducer";
import NameUsReducer from "../name_us_reducer";
import NextRoundReducer from "../next_round_reducer";
import RemoveJokeReducer from "../remove_joke_reducer";
import RemoveScrapReducer from "../remove_scrap_reducer";
import RestReducer from "../rest_reducer";
import RevealRoundReducer from "../reveal_round_reducer";
import RingReducer from "../ring_reducer";
import SealScrapReducer from "../seal_scrap_reducer";
import SendMessageReducer from "../send_message_reducer";
import SendSignalReducer from "../send_signal_reducer";
import SetLayoutReducer from "../set_layout_reducer";
import SetTypingReducer from "../set_typing_reducer";
import StartGameReducer from "../start_game_reducer";
import SubmitAnswerReducer from "../submit_answer_reducer";
import UnlockPlusReducer from "../unlock_plus_reducer";

export type AcceptCallParams = __Infer<typeof AcceptCallReducer>;
export type AddJokeParams = __Infer<typeof AddJokeReducer>;
export type AddScrapParams = __Infer<typeof AddScrapReducer>;
export type BeatParams = __Infer<typeof BeatReducer>;
export type BoardEndParams = __Infer<typeof BoardEndReducer>;
export type BoardMoveParams = __Infer<typeof BoardMoveReducer>;
export type BoardSettleParams = __Infer<typeof BoardSettleReducer>;
export type BoardStartParams = __Infer<typeof BoardStartReducer>;
export type ClearNightParams = __Infer<typeof ClearNightReducer>;
export type ClearThreadParams = __Infer<typeof ClearThreadReducer>;
export type DeleteMessageParams = __Infer<typeof DeleteMessageReducer>;
export type DoodleClearParams = __Infer<typeof DoodleClearReducer>;
export type DoodlePaintParams = __Infer<typeof DoodlePaintReducer>;
export type DoodlePromptParams = __Infer<typeof DoodlePromptReducer>;
export type EditMessageParams = __Infer<typeof EditMessageReducer>;
export type EditScrapParams = __Infer<typeof EditScrapReducer>;
export type EndGameParams = __Infer<typeof EndGameReducer>;
export type HangUpParams = __Infer<typeof HangUpReducer>;
export type MarkNightParams = __Infer<typeof MarkNightReducer>;
export type MarkReadParams = __Infer<typeof MarkReadReducer>;
export type NameUsParams = __Infer<typeof NameUsReducer>;
export type NextRoundParams = __Infer<typeof NextRoundReducer>;
export type RemoveJokeParams = __Infer<typeof RemoveJokeReducer>;
export type RemoveScrapParams = __Infer<typeof RemoveScrapReducer>;
export type RestParams = __Infer<typeof RestReducer>;
export type RevealRoundParams = __Infer<typeof RevealRoundReducer>;
export type RingParams = __Infer<typeof RingReducer>;
export type SealScrapParams = __Infer<typeof SealScrapReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SendSignalParams = __Infer<typeof SendSignalReducer>;
export type SetLayoutParams = __Infer<typeof SetLayoutReducer>;
export type SetTypingParams = __Infer<typeof SetTypingReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type SubmitAnswerParams = __Infer<typeof SubmitAnswerReducer>;
export type UnlockPlusParams = __Infer<typeof UnlockPlusReducer>;

